# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame1")  # Adjusted to a relative path

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def clear_window(window):
    for widget in window.winfo_children():
        widget.destroy()

class BestsellerWindow:
    def __init__(self, window):
        self.window = window
        try:
            print("Initializing window...")
            self.window.geometry("507x782")
            self.window.configure(bg="#FFFFFF")
            
            # Keep a reference to the images to prevent garbage collection
            self.button_images = []
            for i in range(1, 12):
                image = PhotoImage(file=relative_to_assets(f"button_{i}.png"))
                self.button_images.append(image)
            
            canvas = Canvas(
                self.window,
                bg = "#FFFFFF",
                height = 782,
                width = 507,
                bd = 0,
                highlightthickness = 0,
                relief = "ridge"
            )

            canvas.place(x = 0, y = 0)
            canvas.create_text(
                149.518798828125,
                220.4893798828125,
                anchor="nw",
                text="Buffalo Wings",
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                194.2701416015625,
                21.4119873046875,
                anchor="nw",
                text="Best Sellers",
                fill="#000000",
                font=("Abril Fatface", 21 * -1)
            )

            canvas.create_text(
                8.5279541015625,
                184.81707763671875,
                anchor="nw",
                text="Best Sellers",
                fill="#000000",
                font=("Abril Fatface", 16 * -1)
            )

            canvas.create_text(
                3.3973388671875,
                404.287109375,
                anchor="nw",
                text="Other Flavors",
                fill="#000000",
                font=("Abril Fatface", 16 * -1)
            )

            canvas.create_text(
                28.877685546875,
                603.0333862304688,
                anchor="nw",
                text="Drinks",
                fill="#000000",
                font=("Abril Fatface", 16 * -1)
            )

            canvas.create_text(
                141.025390625,
                439.619873046875,
                anchor="nw",
                text="Garlic Parmesan",
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                149.7109375,
                660.4490356445312,
                anchor="nw",
                text="Honey Soy",  # Changed from Sweet & Spicy
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                344.9637451171875,
                660.4490356445312,
                anchor="nw",
                text="Salted Egg",  # Changed from Honey Citrus
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                344.8675537109375,  # Adjusted x-coordinate further to the left
                439.619873046875,
                anchor="nw",
                text="Korean BBQ",  # Changed from BBQ
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                349.9637451171875,
                220.4893798828125,
                anchor="nw",
                text="Soy Garlic",
                fill="#000000",
                font=("Abril Fatface", 14 * -1)
            )

            canvas.create_text(
                558.10498046875,
                238.7806396484375,
                anchor="nw",
                text="Burger",
                fill="#000000",
                font=("Abril Fatface", 12 * -1)
            )

            # Define button functions
            def back_to_menu():
                clear_window(self.window)
                from order import create_main_window_content
                create_main_window_content(self.window)

            def open_buffalo_wings():
                try:
                    print("Opening Buffalo Wings...")
                    clear_window(self.window)
                    from products.Buffalo_wings import create_buffalo_wings_content
                    create_buffalo_wings_content(self.window)
                    print("Buffalo Wings opened successfully.")
                except Exception as e:
                    print(f"Failed to open Buffalo Wings: {e}")

            button_1 = Button(
                self.window,
                image=self.button_images[0],
                borderwidth=0,
                highlightthickness=0,
                command=back_to_menu,
                relief="flat"
            )
            button_1.image = self.button_images[0]  # Keep a reference to the image
            button_1.place(
                x=23.7816162109375,
                y=720.2427368164062,
                width=99.83250427246094,
                height=38.94280242919922
            )

            button_2 = Button(
                self.window,
                image=self.button_images[1],
                borderwidth=0,
                highlightthickness=0,
                command=lambda: print("Opening Cart"),
                relief="flat"
            )
            button_2.image = self.button_images[1]  # Keep a reference to the image
            button_2.place(
                x=370.3135986328125,
                y=721.94140625,
                width=124.00406646728516,
                height=38.58948516845703
            )

            canvas.create_rectangle(
                -0.4979572594165802,
                697.3169596133637,
                507.94146728515625,
                697.9183959960938,
                fill="#000000",
                outline="")

            button_3 = Button(
                self.window,
                image=self.button_images[2],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_drinks,
                relief="flat"
            )
            button_3.image = self.button_images[2]  # Keep a reference to the image
            button_3.place(
                x=23.8160400390625,
                y=536.4450073242188,
                width=60.16745376586914,
                height=60.167457580566406
            )

            canvas.create_rectangle(
                188.55419921875,
                708.3519287109375,
                319.3529968261719,
                772.901985168457,
                fill="#1A4524",
                outline="")

            button_4 = Button(
                self.window,
                image=self.button_images[3],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_buffalo_wings,
                relief="flat"
            )
            button_4.image = self.button_images[3]  # Keep a reference to the image
            button_4.place(
                x=116.0240478515625,
                y=65.73040771484375,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_5 = Button(
                self.window,
                image=self.button_images[4],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_soy_garlic,
                relief="flat"
            )
            button_5.image = self.button_images[4]  # Keep a reference to the image
            button_5.place(
                x=305.2545166015625,
                y=65.73040771484375,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_6 = Button(
                self.window,
                image=self.button_images[5],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_garlic_parmesan,
                relief="flat"
            )
            button_6.image = self.button_images[5]  # Keep a reference to the image
            button_6.place(
                x=116.0244140625,
                y=284.09515380859375,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_7 = Button(
                self.window,
                image=self.button_images[6],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_bbq,
                relief="flat"
            )
            button_7.image = self.button_images[6]  # Keep a reference to the image
            button_7.place(
                x=305.2701416015625,
                y=284.65020751953125,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_8 = Button(
                self.window,
                image=self.button_images[7],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_salted_egg,
                relief="flat"
            )
            button_8.image = self.button_images[7]  # Keep a reference to the image
            button_8.place(
                x=306.2701416015625,
                y=505.65020751953125,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_9 = Button(
                self.window,
                image=self.button_images[8],
                borderwidth=0,
                highlightthickness=0,
                command=self.open_honey_soy,
                relief="flat"
            )
            button_9.image = self.button_images[8]  # Keep a reference to the image
            button_9.place(
                x=116.0240478515625,
                y=505.5736083984375,
                width=148.88934326171875,
                height=148.88937377929688
            )

            button_10 = Button(
                self.window,
                image=self.button_images[9],
                borderwidth=0,
                highlightthickness=0,
                command=lambda: print("button_10 clicked"),
                relief="flat"
            )
            button_10.image = self.button_images[9]  # Keep a reference to the image
            button_10.place(
                x=23.8160400390625,
                y=110.0748291015625,
                width=60.16745376586914,
                height=60.167457580566406
            )

            button_11 = Button(
                self.window,
                image=self.button_images[10],
                borderwidth=0,
                highlightthickness=0,
                command=lambda: print("button_11 clicked"),
                relief="flat"
            )
            button_11.image = self.button_images[10]  # Keep a reference to the image
            button_11.place(
                x=27.178955078125,
                y=327.8463134765625,
                width=60.16745376586914,
                height=60.167457580566406
            )

            # Flavor buttons
            button_4.configure(command=self.open_buffalo_wings)  # Buffalo Wings
            button_5.configure(command=self.open_honey_soy)    # Soy Garlic
            button_6.configure(command=self.open_garlic_parmesan)  # Garlic Parmesan
            button_7.configure(command=self.open_bbq)     # Korean BBQ
            button_8.configure(command=self.open_salted_egg)  # Salted Egg
            button_9.configure(command=self.open_soy_garlic) # Honey Soy
            button_10.configure(command=lambda: print("Opening Best Sellers Menu"))  # Best Sellers menu
            button_11.configure(command=self.open_other_flavors) # Other Flavors menu

            canvas.create_text(
                203.84228515625,
                716.8453369140625,
                anchor="nw",
                text="Order Total",
                fill="#FBFBFB",
                font=("Abril Fatface", 18 * -1)
            )

            canvas.create_text(
                203.84228515625,
                737.2295532226562,
                anchor="nw",
                text="P 999",
                fill="#FBFBFB",
                font=("Abril Fatface", 18 * -1)
            )
            self.window.resizable(False, False)
            print("Window initialized successfully.")
        except Exception as e:
            print(f"An error occurred during window initialization: {e}")

    def open_buffalo_wings(self):
        try:
            print("Opening Buffalo Wings...")
            clear_window(self.window)  # Use clear_window directly
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Buffalo_wings import create_buffalo_wings_content 
            create_buffalo_wings_content(self.window)
            print("Buffalo Wings opened successfully.")
        except Exception as e:
            print(f"Failed to open Buffalo Wings: {e}")

    def open_garlic_parmesan(self):
        try:
            print("Opening Garlic Parmesan...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Garlic_Parmesan import create_garlic_parmesan_content
            create_garlic_parmesan_content(self.window)
            print("Garlic Parmesan opened successfully.")
        except Exception as e:
            print(f"Failed to open Garlic Parmesan: {e}")

    def open_bbq(self):
        try:
            print("Opening Korean BBQ...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Korean_BBQ import create_korean_bbq_content
            create_korean_bbq_content(self.window)
            print("Korean BBQ opened successfully.")
        except Exception as e:
            print(f"Failed to open Korean BBQ: {e}")

    def open_honey_soy(self):
        try:
            print("Opening Soy Garlic...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Soy_Garlic import create_soy_garlic_content
            create_soy_garlic_content(self.window)
            print("Soy Garlic opened successfully.")
        except Exception as e:
            print(f"Failed to open Soy Garlic: {e}")

    def open_salted_egg(self):
        try:
            print("Opening Salted Egg...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Salted_Egg import create_salted_egg_content
            create_salted_egg_content(self.window)
            print("Salted Egg opened successfully.")
        except Exception as e:
            print(f"Failed to open Salted Egg: {e}")

    def open_soy_garlic(self):
        try:
            print("Opening Honey Soy...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent / "products"))
            from Honey_Soy import create_honey_soy_content
            create_honey_soy_content(self.window)
            print("Honey Soy opened successfully.")
        except Exception as e:
            print(f"Failed to open Honey Soy: {e}")

    def open_other_flavors(self):
        try:
            print("Opening Other Flavors...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent))
            from other_flavors import create_other_flavors_content
            create_other_flavors_content(self.window)
            print("Other Flavors opened successfully.")
        except Exception as e:
            print(f"Failed to open Other Flavors: {e}")

    def open_drinks(self):
        try:
            print("Opening Drinks...")
            clear_window(self.window)
            import sys
            sys.path.append(str(Path(__file__).parent))
            from drinks import create_drinks_content
            create_drinks_content(self.window)
            
            # Add a button to go back to the bestseller window
            button_image_back = PhotoImage(file=relative_to_assets("button_1.png"))  # Ensure the correct image is used
            button_back = Button(
                self.window,
                image=button_image_back,
                borderwidth=0,
                highlightthickness=0,
                command=lambda: create_bestseller_content(self.window),
                relief="flat"
            )
            button_back.place(
                x=17.394775390625,
                y=721.94140625,
                width=99.83250427246094,
                height=38.94280242919922
            )
            self.button_images.append(button_image_back)  # Keep a reference to the image
            
            print("Drinks opened successfully.")
        except Exception as e:
            print(f"Failed to open Drinks: {e}")

def create_bestseller_content(window):
    BestsellerWindow(window)
    # No need to return anything

if __name__ == "__main__":
    print("Starting application...")
    try:
        from order import create_main_window
        window = create_main_window()
        create_bestseller_content(window)
        window.mainloop()
    except Exception as e:
        print(f"An error occurred: {e}")
    print("Application closed.")
