
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pilim\Desktop\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("507x782")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 782,
    width = 507,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    149.518798828125,
    220.48944091796875,
    anchor="nw",
    text="Buffalo Wings",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    194.2701416015625,
    21.4119873046875,
    anchor="nw",
    text="Best Sellers",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    8.5279541015625,
    184.81707763671875,
    anchor="nw",
    text="Best Sellers",
    fill="#000000",
    font=("Abril Fatface", 16 * -1)
)

canvas.create_text(
    3.3973388671875,
    404.287109375,
    anchor="nw",
    text="Other Flavors",
    fill="#000000",
    font=("Abril Fatface", 16 * -1)
)

canvas.create_text(
    28.877685546875,
    603.0333862304688,
    anchor="nw",
    text="Drinks",
    fill="#000000",
    font=("Abril Fatface", 16 * -1)
)

canvas.create_text(
    141.025390625,
    439.6199035644531,
    anchor="nw",
    text="Garlic Parmesan",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    159.7108154296875,
    660.4490356445312,
    anchor="nw",
    text="Honey Soy",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    349.9637451171875,
    660.4490356445312,
    anchor="nw",
    text="Salted Egg",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    344.8675537109375,
    439.6199035644531,
    anchor="nw",
    text="Korean BBQ",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    349.9637451171875,
    220.48944091796875,
    anchor="nw",
    text="Soy Garlic",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    558.1048583984375,
    238.7806396484375,
    anchor="nw",
    text="Burger",
    fill="#000000",
    font=("Abril Fatface", 12 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=23.7816162109375,
    y=720.2427368164062,
    width=99.83250427246094,
    height=38.94280242919922
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=370.3135986328125,
    y=721.94140625,
    width=124.00406646728516,
    height=38.58948516845703
)

canvas.create_rectangle(
    -0.4979572594165802,
    697.3169596133637,
    507.94146728515625,
    697.9183959960938,
    fill="#000000",
    outline="")

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=23.8160400390625,
    y=536.4450073242188,
    width=60.16745376586914,
    height=60.167457580566406
)

canvas.create_rectangle(
    188.55419921875,
    708.3519287109375,
    319.3529968261719,
    772.901985168457,
    fill="#1A4524",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=116.0240478515625,
    y=65.73040771484375,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=305.2545166015625,
    y=65.73040771484375,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=116.0244140625,
    y=284.09515380859375,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=305.2701416015625,
    y=284.65020751953125,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat"
)
button_8.place(
    x=306.2701416015625,
    y=505.65020751953125,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat"
)
button_9.place(
    x=116.0240478515625,
    y=505.5736083984375,
    width=148.88934326171875,
    height=148.88937377929688
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat"
)
button_10.place(
    x=23.8160400390625,
    y=110.0748291015625,
    width=60.16745376586914,
    height=60.167457580566406
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat"
)
button_11.place(
    x=27.178955078125,
    y=327.84625244140625,
    width=60.16745376586914,
    height=60.167457580566406
)

canvas.create_text(
    203.84228515625,
    716.8453369140625,
    anchor="nw",
    text="Order Total",
    fill="#FBFBFB",
    font=("Abril Fatface", 18 * -1)
)

canvas.create_text(
    203.84228515625,
    737.2295532226562,
    anchor="nw",
    text="P 999",
    fill="#FBFBFB",
    font=("Abril Fatface", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
