# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame4")  # Use relative path


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def clear_window(window):
    for widget in window.winfo_children():
        widget.destroy()


cart_items = []

def add_to_cart(item_name, quantity, total_price):
    cart_items.append({
        "item_name": item_name,
        "quantity": quantity,
        "total_price": total_price
    })

def create_cart_content(window):
    try:
        print("Starting cart content creation...")
        window.geometry("507x782")
        window.configure(bg = "#FFFFFF")

        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 782,
            width = 507,
            bd = 0,
            highlightthickness=0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)

        canvas.create_text(
            253.5,
            20,
            anchor="center",
            text="Shopping Cart",
            fill="#000000",
            font=("Arial Bold", 24)
        )

        y_position = 80
        total = 0
        for item in cart_items:
            canvas.create_text(
                50,
                y_position,
                anchor="w",
                text=f"{item['item_name']}",
                fill="#000000",
                font=("Arial", 16)
            )
            canvas.create_text(
                300,
                y_position,
                anchor="w",
                text=f"x{item['quantity']}",
                fill="#000000",
                font=("Arial", 16)
            )
            canvas.create_text(
                400,
                y_position,
                anchor="w",
                text=f"₱{item['total_price']}",
                fill="#000000",
                font=("Arial", 16)
            )
            total += item['total_price']
            y_position += 40

        canvas.create_text(
            50,
            700,
            anchor="w",
            text=f"Total: ₱{total}",
            fill="#000000",
            font=("Arial Bold", 18)
        )

        button_image = PhotoImage(
            file=relative_to_assets("button_back.png"))
        button_back = Button(
            window,
            image=button_image,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("Back to previous screen"),  # Define the back button functionality
            relief="flat"
        )
        button_back.place(
            x=20,
            y=700,
            width=100,
            height=40
        )

        # Keep a reference to the images to prevent garbage collection
        window.button_images = [button_image]

        window.resizable(False, False)
        print("Cart content created successfully.")
        return True

    except Exception as e:
        print(f"Error creating cart content: {str(e)}")
        return False

def relative_to_assets(path: str) -> str:
    return f"C:/Users/pilim/Desktop/Ordering/assets/{path}"

# Make the function available for import
__all__ = ['create_cart_content']
