# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import time
import threading
from dsa.order_tracking import OrderQueue, Order

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame6")

order_queue = OrderQueue()

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def clear_window(window):
    for widget in window.winfo_children():
        widget.destroy()


def reset_to_order(window):
    from order import create_main_window_content  # Import the function to create main window content
    clear_window(window)
    create_main_window_content(window)
    next_order_number = order_queue.get_next_order_number()
    if next_order_number:
        create_order_number_content(window, next_order_number)
    else:
        print("No orders to display.")


def create_order_number_content(window, order_number):
    window.geometry("507x782")
    window.configure(bg = "#FFFFFF")

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 782,
        width = 507,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        558.1044921875,
        238.78091430664062,
        anchor="nw",
        text="Burger",
        fill="#000000",
        font=("Abril Fatface", 12 * -1)
    )

    canvas.create_text(
        125.0,
        142.0,
        anchor="nw",
        text="Your Number is",
        fill="#000000",
        font=("Abril Fatface", 36 * -1)
    )

    canvas.create_rectangle(
        129.0,
        232.0,
        378.0,
        342.0,  # Add the missing fourth coordinate
        fill="#D9D9D9",
        outline=""
    )

    canvas.create_text(
        249.0,
        272.0,
        anchor="nw",
        text=str(order_number),  # Display the order number
        fill="#000000",
        font=("Abril Fatface", 21 * -1)
    )

    # Update the order status to "Displayed"
    order_queue.update_order_status(order_number, "Displayed")

    canvas.create_text(
        76.0,
        366.0,
        anchor="nw",
        text="Please proceed to the counter to",
        fill="#1A4524",
        font=("Abril Fatface", 24 * -1)
    )

    canvas.create_text(
        149.0,
        401.0,
        anchor="nw",
        text="claim your receipt.",
        fill="#1A4524",
        font=("Abril Fatface", 24 * -1)
    )

    canvas.create_text(
        120.0,
        505.0,
        anchor="nw",
        text="Thank you!",
        fill="#1A4524",
        font=("Abril Fatface", 48 * -1)
    )

    # Start a timer to reset to order.py after 10 seconds
    threading.Timer(10.0, reset_to_order, args=(window,)).start()

# Remove the creation of a new window
# window = Tk()
# create_order_number_content(window, 1)
# window.resizable(False, False)
# window.mainloop()
