# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from bestseller import create_bestseller_content 

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("assets/frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def create_main_window():
    window = Tk()
    create_main_window_content(window)
    window.resizable(False, False)
    return window

def create_main_window_content(window):
    # Clear the window in case it's being reused
    for widget in window.winfo_children():
        widget.destroy()
    
    window.geometry("507x782")
    window.configure(bg="#FFFFFF")
    
    # Store button images as window attributes to prevent garbage collection
    window.button_images = []
    window.button_images.append(PhotoImage(file=relative_to_assets("button_1.png")))
    window.button_images.append(PhotoImage(file=relative_to_assets("button_2.png")))
    
    canvas = Canvas(
        window,
        bg="#FFFFFF",
        height=782,
        width=507,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )
    canvas.place(x=0, y=0)
    canvas.create_text(
        128.68359375,
        152.5421142578125,
        anchor="nw",
        text="WELCOME TO",
        fill="#2E2E2E",
        font=("Abril Fatface", 33 * -1)
    )
    canvas.create_text(
        103.203369140625,
        198.4066162109375,
        anchor="nw",
        text="HARIBON WINGS",
        fill="#2E2E2E",
        font=("Abril Fatface", 33 * -1)
    )
    canvas.create_rectangle(
        57.27203369140625,
        316.1578369140625,
        207.2025604248047,
        466.08837890625,
        fill="#FFFFFF",
        outline=""
    )
    canvas.create_text(
        106.162353515625,
        497.5954284667969,
        anchor="nw",
        text="Dine-In",
        fill="#2E2E2E",
        font=("Abril Fatface", 21 * -1)
    )
    canvas.create_text(
        314.21875,
        497.5954284667969,
        anchor="nw",
        text="Take-away",
        fill="#2E2E2E",
        font=("Abril Fatface", 21 * -1)
    )
    canvas.create_rectangle(
        40.9755859375,
        293.8853759765625,
        224.04293823242188,
        466.0882263183594,
        fill="#FFFFFF",
        outline=""
    )

    def open_bestseller():
        from bestseller import create_bestseller_content  # Import inside function to avoid circular imports
        create_bestseller_content(window)

    button_1 = Button(
        window,
        image=window.button_images[0],
        borderwidth=0,
        highlightthickness=0,
        command=open_bestseller,
        relief="flat"
    )
    button_1.place(
        x=280.072021484375,
        y=298.6290283203125,
        width=191.9514617919922,
        height=180.06068420410156
    )

    button_2 = Button(
        window,
        image=window.button_images[1],
        borderwidth=0,
        highlightthickness=0,
        command=open_bestseller,
        relief="flat"
    )
    button_2.place(
        x=35.0,
        y=297.144775390625,
        width=195.018310546875,
        height=187.41317749023438
    )

def main():
    window = create_main_window()
    window.mainloop()

if __name__ == "__main__":
    main()
