
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pilim\Desktop\Ordering\assets\frame7")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("507x782")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 782,
    width = 507,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    558.1044921875,
    238.78091430664062,
    anchor="nw",
    text="Burger",
    fill="#000000",
    font=("Abril Fatface", 12 * -1)
)

canvas.create_rectangle(
    -0.4979572594165802,
    697.3170206485199,
    507.94146728515625,
    697.91845703125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    18.5360144674778,
    538.5360166603944,
    459.9996032714844,
    539.08984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    18.5360144674778,
    432.5360166603944,
    459.9996032714844,
    433.08984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    18.5362586081028,
    614.5360166603945,
    459.9998474121094,
    615.08984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    18.5360144674778,
    621.4461729103945,
    459.9996032714844,
    622.0,
    fill="#000000",
    outline="")

canvas.create_text(
    171.0,
    46.0,
    anchor="nw",
    text="Order Summary",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    44.0,
    115.0,
    anchor="nw",
    text="Item name",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    34.0,
    440.0,
    anchor="nw",
    text="Add-Ons :",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    29.0,
    562.0,
    anchor="nw",
    text="Total:",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    29.0,
    562.0,
    anchor="nw",
    text="Total:",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    29.000244140625,
    645.0,
    anchor="nw",
    text="Payment Method: ",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    223.0,
    115.0,
    anchor="nw",
    text="Quantity",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    386.0,
    115.0,
    anchor="nw",
    text="Price",
    fill="#000000",
    font=("Abril Fatface", 21 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=207.0,
    y=721.0,
    width=94.0,
    height=39.58948516845703
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=19.0,
    y=721.0,
    width=83.83250427246094,
    height=38.94280242919922
)

canvas.create_text(
    38.175537109375,
    476.0,
    anchor="nw",
    text="Crispy Fries - ₱30",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    39.455810546875,
    507.29998779296875,
    anchor="nw",
    text="Side Rice - ₱15",
    fill="#000000",
    font=("Abril Fatface", 14 * -1)
)

canvas.create_text(
    267.50439453125,
    509.20965576171875,
    anchor="nw",
    text="1",
    fill="#000000",
    font=("Abril Fatface", 13 * -1)
)

canvas.create_text(
    267.50439453125,
    473.20965576171875,
    anchor="nw",
    text="1",
    fill="#000000",
    font=("Abril Fatface", 13 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=288.0,
    y=508.0,
    width=19.3548641204834,
    height=19.3548641204834
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=288.0,
    y=472.0,
    width=19.3548641204834,
    height=19.3548641204834
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=232.0,
    y=508.0,
    width=19.3548641204834,
    height=19.3548641204834
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=232.0,
    y=472.0,
    width=19.3548641204834,
    height=19.3548641204834
)
window.resizable(False, False)
window.mainloop()
