
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pilim\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("521x782")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 782,
    width = 521,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    147.40087890625,
    152.5421142578125,
    anchor="nw",
    text="WELCOME TO",
    fill="#2E2E2E",
    font=("Abril Fatface", 33 * -1)
)

canvas.create_text(
    121.9205322265625,
    198.4066162109375,
    anchor="nw",
    text="HARIBON WINGS",
    fill="#2E2E2E",
    font=("Abril Fatface", 33 * -1)
)

canvas.create_rectangle(
    68.9892578125,
    316.1578369140625,
    218.91978454589844,
    466.08837890625,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    117.879638671875,
    497.5954284667969,
    anchor="nw",
    text="Dine-In",
    fill="#2E2E2E",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_text(
    325.9359130859375,
    497.5954284667969,
    anchor="nw",
    text="Take-away",
    fill="#2E2E2E",
    font=("Abril Fatface", 21 * -1)
)

canvas.create_rectangle(
    52.69287109375,
    293.8853759765625,
    235.76022338867188,
    466.0882263183594,
    fill="#FFFFFF",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=291.7891845703125,
    y=298.6290283203125,
    width=191.9514617919922,
    height=180.06068420410156
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=46.71722412109375,
    y=297.144775390625,
    width=195.018310546875,
    height=187.41317749023438
)
window.resizable(False, False)
window.mainloop()
