
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\pilim\Desktop\build\assets\frame17")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("507x782")
window.configure(bg = "#A91B0D")


canvas = Canvas(
    window,
    bg = "#A91B0D",
    height = 782,
    width = 507,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=344.1580810546875,
    y=712.177001953125,
    width=139.0,
    height=41.0
)

canvas.create_text(
    558.1048583984375,
    238.780517578125,
    anchor="nw",
    text="Burger",
    fill="#000000",
    font=("Abril Fatface", 12 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=352.1580810546875,
    y=21.177001953125,
    width=126.0,
    height=41.0
)

canvas.create_rectangle(
    -0.4979572594165802,
    697.3170206485202,
    507.94146728515625,
    697.91845703125,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    18.142320811748505,
    322.2070179723996,
    490.920166015625,
    322.750244140625,
    fill="#000000",
    outline="")

canvas.create_text(
    42.4671630859375,
    343.134521484375,
    anchor="nw",
    text="Honey Soy (4pcs)",
    fill="#FFFFFF",
    font=("Abril Fatface", 20 * -1)
)

canvas.create_text(
    42.4671630859375,
    417.876708984375,
    anchor="nw",
    text="Php 999 ",
    fill="#000000",
    font=("Abril Fatface", 20 * -1)
)

canvas.create_text(
    35.67236328125,
    492.619140625,
    anchor="nw",
    text="Golden wings drizzled with a sweet honey and\nsavory soy sauce blend, offering a perfectly\nbalanced flavor.",
    fill="#FFFFFF",
    font=("Abril Fatface", 20 * -1)
)

canvas.create_text(
    107.1580810546875,
    723.177001953125,
    anchor="nw",
    text="1",
    fill="#FFFFFF",
    font=("Abril Fatface", 18 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=137.593505859375,
    y=725.339111328125,
    width=27.178970336914062,
    height=27.178970336914062
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=59.4539794921875,
    y=723.639892578125,
    width=27.178970336914062,
    height=27.178970336914062
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    252.1961669921875,
    197.358154296875,
    image=image_image_1
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=19.1580810546875,
    y=22.177001953125,
    width=33.0,
    height=29.0
)
window.resizable(False, False)
window.mainloop()
